//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALBUM
    {
        public ALBUM()
        {
            this.SONG = new HashSet<SONG>();
        }
    
        public int id { get; set; }
        public string albumName { get; set; }
        public Nullable<System.DateTime> publishDate { get; set; }
        public string albumImage { get; set; }
    
        public virtual ICollection<SONG> SONG { get; set; }
    }
}
