//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA
    {
        public AREA()
        {
            this.SONG = new HashSet<SONG>();
        }
    
        public string id { get; set; }
        public string areaName { get; set; }
    
        public virtual ICollection<SONG> SONG { get; set; }
    }
}
