//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_VIEW_VIDEO
    {
        public int id { get; set; }
        public Nullable<int> videoId { get; set; }
        public Nullable<int> clientId { get; set; }
        public Nullable<int> currentViews { get; set; }
        public Nullable<bool> likeVideo { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual SONG SONG { get; set; }
    }
}
