//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public CLIENT()
        {
            this.CLIENT_LOVE_SONG = new HashSet<CLIENT_LOVE_SONG>();
            this.CLIENT_VIEW_SONG = new HashSet<CLIENT_VIEW_SONG>();
            this.CLIENT_VIEW_VIDEO = new HashSet<CLIENT_VIEW_VIDEO>();
            this.COMMENT = new HashSet<COMMENT>();
            this.FAVORITE_LIST = new HashSet<FAVORITE_LIST>();
            this.PLAYLIST = new HashSet<PLAYLIST>();
        }
    
        public int id { get; set; }
        public string userName { get; set; }
        public string pass { get; set; }
        public string fullName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<bool> VIP { get; set; }
    
        public virtual ICollection<CLIENT_LOVE_SONG> CLIENT_LOVE_SONG { get; set; }
        public virtual ICollection<CLIENT_VIEW_SONG> CLIENT_VIEW_SONG { get; set; }
        public virtual ICollection<CLIENT_VIEW_VIDEO> CLIENT_VIEW_VIDEO { get; set; }
        public virtual ICollection<COMMENT> COMMENT { get; set; }
        public virtual ICollection<FAVORITE_LIST> FAVORITE_LIST { get; set; }
        public virtual ICollection<PLAYLIST> PLAYLIST { get; set; }
    }
}
