//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicAppEntities : DbContext
    {
        public MusicAppEntities()
            : base("name=MusicAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADVERTISEMENT> ADVERTISEMENT { get; set; }
        public DbSet<ALBUM> ALBUM { get; set; }
        public DbSet<AREA> AREA { get; set; }
        public DbSet<CLIENT> CLIENT { get; set; }
        public DbSet<CLIENT_LOVE_SONG> CLIENT_LOVE_SONG { get; set; }
        public DbSet<CLIENT_VIEW_SONG> CLIENT_VIEW_SONG { get; set; }
        public DbSet<CLIENT_VIEW_VIDEO> CLIENT_VIEW_VIDEO { get; set; }
        public DbSet<COMMENT> COMMENT { get; set; }
        public DbSet<FAVORITE_LIST> FAVORITE_LIST { get; set; }
        public DbSet<FAVORITE_LIST_SONG> FAVORITE_LIST_SONG { get; set; }
        public DbSet<PLAYLIST> PLAYLIST { get; set; }
        public DbSet<SINGER> SINGER { get; set; }
        public DbSet<SONG> SONG { get; set; }
        public DbSet<SONG_PLAYLIST> SONG_PLAYLIST { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TOPIC> TOPIC { get; set; }
        public DbSet<USER_LOGIN_CREDENTIAL> USER_LOGIN_CREDENTIAL { get; set; }
        public DbSet<VIDEO> VIDEO { get; set; }
    }
}
