//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVORITE_LIST_SONG
    {
        public int id { get; set; }
        public Nullable<int> favoriteId { get; set; }
        public Nullable<int> songId { get; set; }
    
        public virtual FAVORITE_LIST FAVORITE_LIST { get; set; }
        public virtual SONG SONG { get; set; }
    }
}
