//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYLIST
    {
        public PLAYLIST()
        {
            this.SONG_PLAYLIST = new HashSet<SONG_PLAYLIST>();
        }
    
        public int id { get; set; }
        public string playlistName { get; set; }
        public Nullable<int> clientId { get; set; }
        public string ipAddress { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual ICollection<SONG_PLAYLIST> SONG_PLAYLIST { get; set; }
    }
}
