//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SONG
    {
        public SONG()
        {
            this.CLIENT_LOVE_SONG = new HashSet<CLIENT_LOVE_SONG>();
            this.CLIENT_VIEW_SONG = new HashSet<CLIENT_VIEW_SONG>();
            this.CLIENT_VIEW_VIDEO = new HashSet<CLIENT_VIEW_VIDEO>();
            this.COMMENT = new HashSet<COMMENT>();
            this.FAVORITE_LIST_SONG = new HashSet<FAVORITE_LIST_SONG>();
            this.SONG_PLAYLIST = new HashSet<SONG_PLAYLIST>();
        }
    
        public int id { get; set; }
        public string songName { get; set; }
        public Nullable<int> topicId { get; set; }
        public Nullable<int> albumId { get; set; }
        public Nullable<int> singerId { get; set; }
        public string lyrics { get; set; }
        public string songImage { get; set; }
        public string songCode { get; set; }
        public string areaId { get; set; }
    
        public virtual ALBUM ALBUM { get; set; }
        public virtual AREA AREA { get; set; }
        public virtual ICollection<CLIENT_LOVE_SONG> CLIENT_LOVE_SONG { get; set; }
        public virtual ICollection<CLIENT_VIEW_SONG> CLIENT_VIEW_SONG { get; set; }
        public virtual ICollection<CLIENT_VIEW_VIDEO> CLIENT_VIEW_VIDEO { get; set; }
        public virtual ICollection<COMMENT> COMMENT { get; set; }
        public virtual ICollection<FAVORITE_LIST_SONG> FAVORITE_LIST_SONG { get; set; }
        public virtual SINGER SINGER { get; set; }
        public virtual TOPIC TOPIC { get; set; }
        public virtual ICollection<SONG_PLAYLIST> SONG_PLAYLIST { get; set; }
    }
}
