//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SONG_PLAYLIST
    {
        public int id { get; set; }
        public Nullable<int> playlistId { get; set; }
        public Nullable<int> songId { get; set; }
    
        public virtual PLAYLIST PLAYLIST { get; set; }
        public virtual SONG SONG { get; set; }
    }
}
