//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOPIC
    {
        public TOPIC()
        {
            this.CATEGORY = new HashSet<CATEGORY>();
            this.SONG = new HashSet<SONG>();
            this.VIDEO = new HashSet<VIDEO>();
        }
    
        public int id { get; set; }
        public string topicName { get; set; }
        public string topicImage { get; set; }
    
        public virtual ICollection<CATEGORY> CATEGORY { get; set; }
        public virtual ICollection<SONG> SONG { get; set; }
        public virtual ICollection<VIDEO> VIDEO { get; set; }
    }
}
