//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO
    {
        public int id { get; set; }
        public string videoName { get; set; }
        public string videoImage { get; set; }
        public string videoDesc { get; set; }
        public Nullable<int> topicId { get; set; }
        public Nullable<int> categoryId { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual TOPIC TOPIC { get; set; }
    }
}
